### ISSUE TITLE
Null pointer on loading data

### ISSUE THREAD

**Issue by pgwilliams** [IHTSDO/OTF-Mapping-Service#43]
Tom wrote to IHTSDO with the following issue which has been partially discussed via our internal issue tracking system.   Full stack trace included at the end:

**TOM**:  On loading SCT into the mapping tool (according to step 7 on https://confluence.ihtsdotools.org/display/MT/Building+and+Deploying+in+Eclipse) the following error occurs:  [ERROR] Failed to execute goal org.ihtsdo.otf.mapping:mapping-admin-mojo:1.0.10-SNAPSHOT:load-rf2-snapshot (load-rf2-snapshot) on project mapping-admin-loader: Unexpected exception: NullPointerException -> [Help 1]   The full error is added it this email.   Can you help me fix this?

**KAI**: Is this the first time you are attempting the load the data?  It could be worth trying running truncate_all.sql and trying again. From the documentation: "NOTE: if re-running this, you first have to run the sql in "truncate_all.sql" to clear your database of tables."

**TOM**: I tried that already, same error occurs at the same time in the dev-windows build as well as in the prod build.

`------------------------------------------------
## Starting ...Thu May 26 01:14:47 PDT 2016

MAPPING_CODE = /home/tom/Code
MAPPING_DATA = /home/tom/Code
MAPPING_CONFIG = /home/tom/Code
    Run updatedb with hibernate.hbm2ddl.auto = create ...Thu May 26 01:14:47 PDT 2016
    Clear indexes ...Thu May 26 01:15:01 PDT 2016
    Load SNOMEDCT ...Thu May 26 01:15:12 PDT 2016
ERROR loading SNOMEDCT
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building OTF RF2 Admin RF2 Loader 1.0.10-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- mapping-admin-mojo:1.0.10-SNAPSHOT:load-rf2-snapshot (load-rf2-snapshot) @ mapping-admin-loader ---
[INFO] Starting loading RF2 data
[INFO]   inputDir = /home/tom/Data/snomedct-20140731-snapshot
[INFO]   terminology = SNOMEDCT
[INFO]   sendNotification = false
2016-05-26_01:15:17.108 INFO -   run.config = /home/tom/Config/config.properties
2016-05-26_01:15:17.114 INFO -   properties = {workflow.path.handler.NON_LEGACY_PATH.class=org.ihtsdo.otf.mapping.jpa.handlers.WorkflowNonLegacyPathHandler, loader.defaultPreferredNames.typeId=900000000000003001, mail.smtp.starttls.enable=true, index.viewer.subSubSearchEndLevel=2, mail.smtp.auth=true, mail.smtp.to.feedback.user=____*_, hibernate.jdbc.default_batch_fetch_size=16, mail.smtp.password=____*_, workflow.path.handler=NON_LEGACY_PATH,LEGACY_PATH,REVIEW_PROJECT_PATH,FIX_ERROR_PATH,QA_PATH,SIMPLE_PATH, javax.persistence.jdbc.user=root, send.notification.recipients=____*_    , metadata.service.handler.GMDN.class=org.ihtsdo.otf.mapping.jpa.services.ClamlMetadataServiceJpaHelper, base.url.webapp=http://localhost:8080/mapping-webapp, deploy.footer.link=http://www.ihtsdo.org/, loader.defaultPreferredNames.refSetId=900000000000509007, javax.persistence.jdbc.password=____*_, hibernate.search.default.indexBase=/home/tom/Data, metadata.service.handler.ICPC.class=org.ihtsdo.otf.mapping.jpa.services.ClamlMetadataServiceJpaHelper, metadata.service.handler.ICD10.class=org.ihtsdo.otf.mapping.jpa.services.ClamlMetadataServiceJpaHelper, index.viewer.data=/home/tom/Data/ihtsdo-mapping-tool-data/indexViewerData, index.viewer.linkSubstitutions=s/Complications/Complication/;, index.viewer.searchStartLevel=0, mail.smtp.user=____*_  , workflow.path.handler.SIMPLE_PATH.class=org.ihtsdo.otf.mapping.jpa.handlers.WorkflowSimplePathHandler, metadata.service.handler.SNOMEDCT.class=org.ihtsdo.otf.mapping.jpa.services.SnomedMetadataServiceJpaHelper, index.viewer.subSubSearchStartLevel=2, javax.persistence.jdbc.url=jdbc:mysql://127.0.0.1:3306/mappingservicedb, index.viewer.artifactId=index-viewer-data-empty, metadata.service.handler=SNOMEDCT,SNOMEDCT_US,ICD10,ICD10CM,ICD9CM,ICPC,GMDN, javax.persistence.jdbc.driver=com.mysql.jdbc.Driver, ihtsdo.security.activated=false, mail.smtp.port=587, workflow.path.handler.REVIEW_PROJECT_PATH.class=org.ihtsdo.otf.mapping.jpa.handlers.WorkflowReviewProjectPathHandler, loader.defaultPreferredNames.acceptabilityId=900000000000548007, deploy.title=IHTSDO Mapping Tool - DEV, hibernate.format_sql=true, deploy.footer.copyright=Copyright @2015 IHTSDO, base.url=http://localhost:8080/mapping-rest, index.viewer.searchEndLevel=0, index.viewer.maxHits=10000, hibernate.use_sql_comments=true, hibernate.show_sql=false, workflow.path.handler.FIX_ERROR_PATH.class=org.ihtsdo.otf.mapping.jpa.handlers.WorkflowFixErrorPathHandler, map.principle.source.document.dir=/home/tom/Data/doc, hibernate.dialect=org.hibernate.dialect.MySQLDialect, index.viewer.phonet=./config/dict/phonet.en, index.viewer.version=1.3.0-SNAPSHOT, index.viewer.groupId=org.ihtsdo.otf.mapping, workflow.path.handler.QA_PATH.class=org.ihtsdo.otf.mapping.jpa.handlers.WorkflowQaPathHandler, metadata.service.handler.ICD10CM.class=org.ihtsdo.otf.mapping.jpa.services.ClamlMetadataServiceJpaHelper, workflow.path.handler.LEGACY_PATH.class=org.ihtsdo.otf.mapping.jpa.handlers.WorkflowLegacyPathHandler, hibernate.jdbc.batch_size=30, index.viewer.subSearchStartLevel=1, hibernate.search.lucene_version=LUCENE_36, index.viewer.subSearchEndLevel=1, mail.smtp.host=____*_, metadata.service.handler.SNOMEDCT_US.class=org.ihtsdo.otf.mapping.jpa.services.SnomedMetadataServiceJpaHelper, metadata.service.handler.ICD9CM.class=org.ihtsdo.otf.mapping.jpa.services.ClamlMetadataServiceJpaHelper, hibernate.search.default.directory_provider=filesystem, mail.smtp.to=____*_ }
[INFO] No notifications will be sent as a result of workflow computation.
[INFO] Request to send notification email for any errors to recipients: ____*_  
[INFO]   terminology = SNOMEDCT
[INFO]   version = latest
[INFO]   Default preferred name settings:
[INFO]     typeId = 900000000000003001
[INFO]     refsetId = 900000000000509007
[INFO]     acceptabilityId = 900000000000548007
[INFO]   Objects committed in blocks of 1000
[INFO] MEMORY USAGE:
[INFO]  Total: 48693248
[INFO]  Free:  29550368
[INFO]  Max:   758251520
[INFO]   Sorting input files...
[INFO]     Sorted files exist and are up to date.  No sorting required
[INFO]       complete in 0s
2016-05-26_01:15:17.117 INFO - Instantiate org.ihtsdo.otf.mapping.jpa.services.SnomedMetadataServiceJpaHelper
2016-05-26_01:15:17.122 INFO - Setting root service entity manager factory.
2016-05-26_01:15:21.795 INFO -  property class = org.ihtsdo.otf.mapping.jpa.services.SnomedMetadataServiceJpaHelper
2016-05-26_01:15:21.796 INFO - Instantiate org.ihtsdo.otf.mapping.jpa.services.SnomedMetadataServiceJpaHelper
2016-05-26_01:15:21.796 INFO -  property class = org.ihtsdo.otf.mapping.jpa.services.SnomedMetadataServiceJpaHelper
2016-05-26_01:15:21.796 INFO - Instantiate org.ihtsdo.otf.mapping.jpa.services.ClamlMetadataServiceJpaHelper
2016-05-26_01:15:21.797 INFO -  property class = org.ihtsdo.otf.mapping.jpa.services.ClamlMetadataServiceJpaHelper
2016-05-26_01:15:21.798 INFO - Instantiate org.ihtsdo.otf.mapping.jpa.services.ClamlMetadataServiceJpaHelper
2016-05-26_01:15:21.798 INFO -  property class = org.ihtsdo.otf.mapping.jpa.services.ClamlMetadataServiceJpaHelper
2016-05-26_01:15:21.798 INFO - Instantiate org.ihtsdo.otf.mapping.jpa.services.ClamlMetadataServiceJpaHelper
2016-05-26_01:15:21.799 INFO -  property class = org.ihtsdo.otf.mapping.jpa.services.ClamlMetadataServiceJpaHelper
2016-05-26_01:15:21.799 INFO - Instantiate org.ihtsdo.otf.mapping.jpa.services.ClamlMetadataServiceJpaHelper
2016-05-26_01:15:21.799 INFO -  property class = org.ihtsdo.otf.mapping.jpa.services.ClamlMetadataServiceJpaHelper
2016-05-26_01:15:21.799 INFO - Instantiate org.ihtsdo.otf.mapping.jpa.services.ClamlMetadataServiceJpaHelper
2016-05-26_01:15:21.799 INFO -  property class = org.ihtsdo.otf.mapping.jpa.services.ClamlMetadataServiceJpaHelper
java.lang.NullPointerException
    at org.ihtsdo.otf.mapping.jpa.services.SnomedMetadataServiceJpaHelper.getHierarchicalRelationshipTypes(SnomedMetadataServiceJpaHelper.java:319)
    at org.ihtsdo.otf.mapping.jpa.services.MetadataServiceJpa.getHierarchicalRelationshipTypes(MetadataServiceJpa.java:345)
    at org.ihtsdo.otf.mapping.mojo.TerminologyRf2SnapshotLoaderMojo.execute(TerminologyRf2SnapshotLoaderMojo.java:331)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
java.lang.NullPointerException
    at org.ihtsdo.otf.mapping.jpa.services.SnomedMetadataServiceJpaHelper.getHierarchicalRelationshipTypes(SnomedMetadataServiceJpaHelper.java:319)
    at org.ihtsdo.otf.mapping.jpa.services.MetadataServiceJpa.getHierarchicalRelationshipTypes(MetadataServiceJpa.java:345)
    at org.ihtsdo.otf.mapping.mojo.TerminologyRf2SnapshotLoaderMojo.execute(TerminologyRf2SnapshotLoaderMojo.java:331)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.924 s
[INFO] Finished at: 2016-05-26T01:15:22-07:00
[INFO] Final Memory: 18M/46M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.ihtsdo.otf.mapping:mapping-admin-mojo:1.0.10-SNAPSHOT:load-rf2-snapshot (load-rf2-snapshot) on project mapping-admin-loader: Unexpected exception: NullPointerException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException`

**Comment by granvold** [comment]
Hi Peter,

 

First, an NPE. How embarrassing!

 

From the log provided, the problem appears to be that content is not properly being loaded into the database. I would expect to see a variety of lines like:

Loading Concepts …

  2000 complete

  4000 complete

  6000 complete ..

Loading Descriptions ..

Loading Relationships …

 

And so forth.  Specifically, at the point of failure, the metadata handler is expecting the concept representing the IsA relationship to exist and is failing to retrieve it.  

 

The most likely cause of failure will lie with the sorted RF2 files that are automatically generated by the loader. Looking back at our code, I’m realizing that we have a pretty bad check for whether or not to sort files based on modification dates … I’ll make a ticket for this. Basically the loader is incorrectly assuming that pre-sorted files exist and can be used, when they don’t and can’t.

 

In the meantime, the problem should be solved by the following:

(1)    Check for the existence of folder /home/tom/Data/snomedct-20140731-snapshot/RF2-sorted-temp

(2)    Delete this folder

(3)    Re-run the loader.

(4)    The files should be re-sorted and the load should continue normally.

(5)    On any subsequent cancellations or re-loads, repeat that deletion …. Just to be safe.

 

Let me know if that helps!

 

Cheers,

Patrick

**Comment by granvold** [comment]
Another possible cause of this may be the file structure.  The Mapping Tool is pretty unforgiving here. The directory structure of the input data must be:

/home/tom/Data/snomedct-20140731-snapshot
     /Terminology
        [files]
     /Refset
          /Content
              [files]
          /Map
              [files]

Please note that the above comment about deleting the RF2-sorted-temp still applies here, i.e. delete that folder before restarting the load.

**Comment by Delnoy** [comment]
Hi,

I deleted the folder and just to be sure I also downloaded the dataset from the gitlab site. 

On rerun the following error shows:
[ERROR] Failed to execute goal org.ihtsdo.otf.mapping:mapping-admin-mojo:1.0.10-SNAPSHOT:load-rf2-snapshot (load-rf2-snapshot) on project mapping-admin-loader: Unexpected exception: Specified input dir missing -> [Help 1]

**Comment by granvold** [comment]
Hrmm.... You should only see that error if the input directory you specify literally does not exist.Possible naming error? That's the first check of the loader.

**Comment by granvold** [comment]
Tom:

I've managed to recreate the problem using the supplied loader scripts. I'm looking into it and will update you once I've pushed a fix.

Thanks for bringing this to our attention!

**Comment by granvold** [comment]
I've identified the problem and am testing the fix now. We have a minimal release process to go through before redeployment; I'll update here once that's done.

**Comment by Delnoy** [comment]
Just one other issue that i noticed during the installation, i used a little workaround to get my installation to continue:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:unpack (unpack-index-viewer-data) on project mapping-webapp: Unable to find artifact. Could not find artifact org.ihtsdo.otf.mapping:index-viewer-data-empty:zip:1.4.0-SNAPSHOT

If i browse to https://nexus.ihtsdotools.org/content/repositories/releases/org/ihtsdo/otf/mapping/index-viewer-data-icd10/ there is a zip file for 1.3.0 release but no file for 1.4.0.

After editing file dev-windows/src/main/resources/config-test.properties to accept the 1.3.0 file and manually installing the file 1.3.0 the installation continues.

**Comment by Delnoy** [comment]
Hi Everyone,

Any progress on this bug?

Thanks!

**Comment by bcarlsenca** [comment]
Yes, Patrick indicated that this was fixed.  We also updated the dev-windows configuration to use the "empty" index viewer config version 1.0.0 - just to keep it simple - which should also be in nexus.ihtsdotools.org.  Let us know if you continue to have a problem.

**Comment by rorydavidson** [comment]
Closing due to inactivity on this thread.
